- hosts: bastion
  become: true
  gather_facts: no
  user: ec2-user
  module_defaults:
    group/aws:
      region: "us-west-1"
  vars:
    ansible_python_interpreter:  /usr/bin/python3
    host_name: "{{ lookup('file', 'rds.txt')}}"

  tasks:
    - name: Wait until the all packages installed
      wait_for:
        path: packages_installed.txt

    - name: debug
      debug: var=ansible_python_interpreter

    - name: debug
      debug: var=host_name

    - name: Connect to database
      postgresql_db:
        name: "image_gallery"
        login_host: "{{host_name}}"
        login_user: "postgres"
        login_password: "postgres"
        state: present
      register: db_ig

    #    - name: debug
    #      debug: var=db_ig

    - name: Create user for image gallery
      postgresql_user:
        db: "image_gallery"
        login_host: "{{host_name}}"
        login_user: "postgres"
        login_password: "postgres"
        name: "image_gallery"
        password: "auburnmod5"
        no_password_changes: no
        priv: "CREATE/CONNECT"
        role_attr_flags: CREATEDB
      register: db_ig_user




    - name: Grant roles to postgres
      postgresql_query:
        db: "image_gallery"
        login_host: "{{host_name}}"
        login_user: "postgres"
        login_password: "postgres"
        query: grant image_gallery to postgres
      register: grant_role

    - name: Create table for image gallery
      postgresql_table:
        db: image_gallery
        login_host: "{{host_name}}"
        login_user: image_gallery
        login_password: "auburnmod5"
        name: users
        owner: image_gallery
        columns:
          - username varchar(100) primary key
          - password varchar(100)
          - full_name varchar(100)
      register: users_table

    - name: Insert names to image_gallery
      postgresql_query:
        db: "image_gallery"
        login_host: "{{host_name}}"
        login_user: "image_gallery"
        login_password: "auburnmod5"
        query: insert into users (username, password, full_name) values ("dom", "fred", "sam");
      register: db_names

    - name: debug
      debug: var=db_names



