- hosts: bastion
  become: true
  gather_facts: no
  user: ec2-user
  module_defaults:
      group/aws:
        region: "us-west-1"
  vars:
    ansible_python_interpreter:  /usr/bin/python3
    host_name: "{{ lookup('file', 'rds.txt')}}"

  tasks:
    - name: Wait until the all packages installed
      wait_for:
        path: packages_installed.txt

    - name: debug
      debug: var=ansible_python_interpreter

    - name: debug
      debug: var=host_name

    - name: Connect to database
      postgresql_db:
        name: image_gallery
        login_host: "{{host_name}}"
        login_user: postgres
        login_password: postgres
        state: present
      register: db_ig

    - name: debug
      debug: var=db_ig

    - name: Create user for image gallery
      postgresql_user:
        db: image_gallery
        login_host: "{{host_name}}"
        login_user: postgres
        login_password: postgres
        name: image_gallery
        no_password_changes: no
        password: "{{ lookup('aws_secret', 'sec-mod-5')}}"
        priv: "CONNECT/image_gallery:ALL"

    - name:
      postgresql_table:
        name: users
        owner: image_gallery
        columns:
          - username varchar(100) primary key
          - password varchar(100)
          - full_name varchar(100)
      register: users_table

    - name: Insert query to image_gallery
      postgresql_query:
        db: image_gallery
        query: insert into users (username, password, full_name) values(%s, %s, %s);

