- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:

    - name: Create public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-public-sn1
          Project: 5
        cidr: 10.0.1.0/24
        az: "{{ aws_region + 'a'}}"
        state: present
      register: public_subnet_1

    - name: Create public subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-public-sn2
          Project: 5
        cidr: 10.0.2.0/24
        az: "{{ aws_region + 'c'}}"
        state: present
      register: public_subnet_2

    - name: Create private subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-private-sn1
          Project: 5
        cidr: 10.0.3.0/24
        az: "{{ aws_region + 'a'}}"
        state: present
      register: private_subnet_1

    - name: Create private subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-private-sn2
          Project: 5
        cidr: 10.0.4.0/24
        az: "{{ aws_region + 'c'}}"
        state: present
      register: private_subnet_2

    - name: Create secrets in subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-secrets-in-sn
          Project: 5
        cidr: 10.0.5.0/24
        az: "{{ aws_region + 'a'}}"
        state: present
      register: secrets_in_subnet

    - name: Create secrets out subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-secrets-out-sn
          Project: 5
        cidr: 10.0.6.0/24
        az: "{{ aws_region + 'c'}}"
        state: present
      register: secrets_out_subnet

