- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Create nlb target group
      elb_target_group:
        name: ans-tg4
        protocol: TCP
        port: 80
        vpc_id: "{{ vpc.vpc.id }}"
#        target_type: instance
        state: present
        wait_timeout: 300
        wait: True
        stickiness_type: source_ip
        stickiness_enabled: no
      register: ans_tg