- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Provision Db Instance
      ec2:
        key_name: zum
        assign_public_ip: yes
        user_data: "{{ lookup('file', './ansible_script.sh') }}"
        group:
          - "{{postgres_tag_sg.group_name}}"
          - "{{nginx_sg.group_name}}"
          - "{{dev_sg.group_name}}"
        instance_type: t2.micro
        wait: yes
        wait_timeout: 500
        region: "{{ aws_region }}"
        image: "{{ ami_id }}"
        instance_profile_name: image-gallery-server-role
        instance_tags:
          Name: provision_postgres_instance
        vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
        exact_count: 1
        count_tag:
          Name: provision_postgres_instance
      register: ec2
- local_action: copy content="{{ ans_rds }}" dest=rds.txt
#    - local_action: copy content="{{ ans_rds.publi }}" dest=rds.txt
    #    - name: debug
    #      debug: var=db_sql
    #


#    - name: sleep for 300 seconds and continue with play
#      wait_for:
#        timeout: 300

