- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Create rds subnet
      rds_subnet_group:
        state: present
        name: ans-rds-subnet
        description: private subnet for ansible rds
        subnets:
          - "{{private_subnet_1.subnet.id}}"
          - "{{private_subnet_2.subnet.id}}"
      register: rds_sng


    - name: Create db
      rds:
        command: create
        db_name: ansibleimagedb
        instance_name: ansibleimagedbnew
        instance_type: db.t2.micro
        size: '10'
        db_engine: postgres
        region: "{{ aws_region }}"
        zone: "{{ aws_region + 'a' }}"
        subnet: ans-rds-subnet
        vpc_security_groups:  "{{postgres_sg.group_id}}"
        username: postgres
        password: postgres
        tags:
          name: ansible_db
      register: ans_rds

    - name: debug
      debug: var=ans_rds
#
    - name: Add sql params
      blockinfile:
        path: /ec2-scripts/ec2_db_provisions.sh
        block: |
          #!/usr/bin/bash
          psql -h "{{ans_rds.instance.endpoint}}" - U postgres -d postgres
          create user image_gallery login password{ lookup('aws_secret', 'ans-sec-ig') }};
          grant image_gallery to postgres;
          create database image_gallery owner image_gallery;
          create table users (username varchar(100) not null primary key, password varchar(100), full_name varchar(200));
        state: present

    - name: Copy rds enpoint
      local_action:
        module: copy
        content: "{{ ans_rds.instance.endpoint }}"
        dest: rds-ep.txt

    - name: Copy rds name
      local_action:
        module: copy
        content: "{{ ans_rds.instance.db_name }}"
        dest: rds-name.txt



#