- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Create rds subnet
      rds_subnet_group:
        state: present
        name: ans-rds-subnet
        description: private subnet for ansible rds
        subnets:
          - "{{private_subnet_1.subnet.id}}"
          - "{{private_subnet_2.subnet.id}}"
      register: rds_sng


    - name: Create db
      rds:
        command: create
        instance_name: ansibleimagedb2
        instance_type: db.t2.micro
        size: '10'
        db_engine: postgres
        region: "{{ aws_region }}"
        zone: "{{ aws_region + 'a' }}"
        subnet: ans-rds-subnet
        vpc_security_groups:  "{{postgres_sg.group_id}}"
        username: postgres
        password: "{{ lookup('aws_secret', 'sec-ans-ig') }}"
#        wait: yes
#        wait_timeout: 600
        tags:
          name: ansible_db
      register: ans_rds

    - name: debug
      debug: var=ans_rds

    - name:
      rds_instance_info:
        db_instance_identifier: "{{ans_rds.db_instance_identifier}}"
      register: db_info

#    - name: Create user test and grant group user_ro and user_rw to it
#      postgresql_user:
#        name: test
#        groups:
#          - user_ro
#          - user_rw
  #
    #    - name: Create new db from snapshot
    #      rds:
    #        command: modifygit stat
    #        instance_name: image_gallery_ans
    #        db_engine: postgres
    #        size: 10
    #        instance_type: db.t2.micro
    #        username: postgres
    #        password: postgres
    #        tags:
    #          Name: ansible-db
    #      register: ans_db
    #    - name: Get db name
    #      rds_instance_info:
    #        db_instance_identifier: image-gallery
    #        register: image_gallery
    #
    #    - name: Create snapshot of db
    #      rds_snapshot:
    #        db_instance_identifier: "{{image_gallery.db_instance_identifier}}"
    #        db_snapshot_identifier: "{{image_gallery.db_snapshot_identifier}}"
    #      register: db_snap


#
#    - name: Create RDS instance with aws secret lookup for password param
#      rds:
#        command: create
#        instance_name: AnsibleImageGallery
#        db_engine: postgres
#        size: 10
#        instance_type: db.t2.micro
#        username: postgres
#        password: postgres
#        tags:
#          Name: AnsibleDb
#      register: ans_db
#
#    - name: Get db name
#      rds_instance_info:
#        db_instance_identifier: image-gallery
#     register: image_gallery
#
#    - name: Create snapshot of db
#      rds_snapshot:
#        db_instance_identifier: "{{image_gallery.db_instance_identifier}}"
#        db_snapshot_identifier: "{{image_gallery.db_snapshot_identifier}}"
#      register: db_snap
##
#    - name: Create new db from snapshot
#      rds:
#        command: modifygit stat
#        instance_name: image_gallery_ans
#        db_engine: postgres
#        size: 10
#        instance_type: db.t2.micro
#        username: postgres
#        password: postgres
#        tags:
#          Name: ansible-db
#      register: ans_db