- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Create an ec2 launch template
      ec2_launch_template:
        name: "ansible_template"
        image_id: "ami-04e59c05167ea7bd5"
        key_name: zum
        instance_type: t2.micro
        iam_instance_profile: image-gallery-server-role
        monitoring:
          enabled: yes
        network_interfaces:
        - device_index: 0
          associate_public_ip_address: yes
          delete_on_termination: yes
          groups:
            - "{{postgres_tag_sg.group_id}}"
            - "{{dev_sg.group_id}}"
            - "{{nginx_sg.group_id}}"
        user_data: "{{ lookup('file', './ec2-scripts/ec2-prod-bootstrap.sh') | b64encode }}"
        state: present
      register: ans_launch_template

    - name: Provision Db Instance
      ec2:
        key_name: zum
        assign_public_ip: yes
        group:
          - "{{postgres_tag_sg.group_name}}"
          - "{{nginx_sg.group_name}}"
          - "{{dev_sg.group_name}}"
        instance_type: t2.micro
        image: "{{ ami_id }}"
        instance_tags:
          Name: provision_postgres_instance
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
        exact_count: 1
        user_data: "{{ lookup('file', './ec2-scripts/ec2-prod-bootstrap.sh') }}"
        count_tag:
          Name: ans_Db_sql
      register: db_sql

