- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
#    - name: Create eip 1 for load balancer
#      ec2_eip:
#        state: present
#        region: "{{ aws_region }}"
#      register: nlb_eip_1
#
#    - name: Create eip 2 for load balancer
#      ec2_eip:
#        state: present
#        region: "{{ aws_region }}"
#      register: nlb_eip_2

    - name: Create eip 1 for load balancer
      ec2_eip_info:
        filters:
          tag:Name: eip_1
      register: nlb_eip_1

    - name: Create eip 2 for load balancer
      ec2_eip_info:
        filters:
          tag:Name: eip_2
      register: nlb_eip_2
