- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"

  pg_secret: {
    "username": "postgres",
    "password": "{{ pg_user_pass }}",
    "engine": "postgres",
    "host": "{{ ans_rds.instance.endpoint }}",
    "port": 5432,
    "dbInstanceIdentifier": "M5-image-gallery",
    "db_name": "image_gallery"
  }
module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    aws_secret:
      name: 'sec-m5-postgres'
      state: present
      secret_type: 'string'
      secret: '{{ pg_secret | to_json }}'