- hosts: localhost
  gather_facts: no
  tasks:
    - name: Include vars of create_vpc.yaml
        include_vars:
          file: create_vpc.yaml
          name: aws_region
    - name: Create public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-public-sn1
          Project: 5
        cidr: 10.0.1.0/24
        az: "{{ aws_region + 'a'}}"
        state: present
      register: public_subnet_1

    - name: Create public subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-public-sn2
          Project: 5
        cidr: 10.0.2.0/24
        az: "{{ aws_region + 'c'}}"
        state: present
      register: public_subnet_2

    - name: Create private subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-private-sn1
          Project: 5
        cidr: 10.0.3.0/24
        az: "{{ aws_region + 'a'}}"
        state: present
      register: private_subnet_1

    - name: Create private subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-private-sn2
          Project: 5
        cidr: 10.0.4.0/24
        az: "{{ aws_region + 'c'}}"
        state: present
      register: private_subnet_2

    - name: Create secrets in subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-secrets-in-sn
          Project: 5
        cidr: 10.0.5.0/24
        az: "{{ aws_region + 'a'}}"
        state: present
      register: secrets_in_subnet

    - name: Create secrets out subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: ans-secrets-out-sn
          Project: 5
        cidr: 10.0.6.0/24
        az: "{{ aws_region + 'c'}}"
        state: present
      register: secrets_out_subnet

#    - name: Create internet gateway
#      ec2_vpc_igw:
#        vpc_id: "{{vpc.vpc.id}}"
#        tags:
#          Name: Ansible Project5 gateway
#          Project: 5
#        region: "{{ aws_region }}"
#        state: present
#      register: igw
#
#    - name: Create NAT gateway
#      ec2_vpc_nat_gateway:
#        subnet_id: "{{ public_subnet_1.subnet.id }}"
#        wait: yes
#        tags:
#          Name: Ansible-ng
#          Project: 5
#        region: "{{ aws_region }}"
#        if_exist_do_not_create: yes
#        state: present
#      register: nat
#    - name: debug
#      debug: var=nat
#
#
#    - name: Create public route table
#      ec2_vpc_route_table:
#        vpc_id: "{{vpc.vpc.id}}"
#        region: "{{ aws_region }}"
#        tags:
#          Name: Ansible-public-rt
#          Project: 5
#        subnets:
#          - "{{ public_subnet_1.subnet.id}}"
#          - "{{ public_subnet_2.subnet.id}}"
#        routes:
#          - dest: 0.0.0.0/0
#            gateway_id: "{{ igw.gateway_id }}"
#        state: present
#      register: public_route_table
#    - name: debug
#      debug: var=public_route_table
#
#
#
#    - name: Create private route table 1
#      ec2_vpc_route_table:
#        vpc_id: "{{vpc.vpc.id}}"
#        region: "{{ aws_region }}"
#        tags:
#          Name: Ansible-private-rt-1
#          Project: 5
#        subnets:
#          - "{{ private_subnet_1.subnet.id}}"
#        routes:
#          - dest: 0.0.0.0/0
#            gateway_id: "{{ nat.nat_gateway_id }}"
#        state: present
#      register: private_nat_route_table_1
#    - name: debug
#      debug: var=private_nat_route_table_1
#
#    - name: Create private route table 2
#      ec2_vpc_route_table:
#        vpc_id: "{{vpc.vpc.id}}"
#        region: "{{ aws_region }}"
#        tags:
#          Name: Ansible-private-rt-2
#          Project: 5
#        subnets:
#          - "{{ private_subnet_2.subnet.id}}"
#        routes:
#          - dest: 0.0.0.0/0
#            gateway_id: "{{ nat.nat_gateway_id }}"
#        state: present
#      register: private_nat_route_table_2
#    - name: debug
#      debug: var=private_nat_route_table_2

#
#
#    - name: Create nginx servers security group
#      ec2_group:
#        name: ans-nginx-servers-sg
#        region: "{{ aws_region }}"
#        description: Nginx servers security group
#        vpc_id: "{{vpc.vpc.id}}"
#        tags:
#          Name: ans-nginx-servers-sg
#          Project: 5
#        rules:
#          - proto: tcp
#            ports: 80
#            cidr_ip:
#              - 68.105.121.53/32
#              - 24.196.25.139/32
#            rule_desc: allow inbound ips on port 80
#          - proto: tcp
#            ports:
#              - 443
#              - 22
#            cidr_ip: 0.0.0.0/0
#            rule_desc: allow all inbound to ports 22 and 443
#        state: present
#      register: nginx_sg
#
#    - name: Create development security group
#      ec2_group:
#        name: ans-development-sg
#        region: "{{ aws_region }}"
#        description: Development security group
#        vpc_id: "{{vpc.vpc.id}}"
#        tags:
#          Name: ans-development-sg
#          Project: 5
#        rules:
#          - proto: tcp
#            ports:
#              - 80
#              - 22
#            cidr_ip: 0.0.0.0/0
#            rule_desc: allow inbound ips on port 80
#          - proto: tcp
#            ports:
#              - 5000
#            cidr_ip: 68.105.121.53/32
#            rule_desc: allow all inbound from personal ip to 5000
#        state: present
#      register: dev_sg
#
#
#    - name: Create secrets security group
#      ec2_group:
#        name: ans-secrets-sg
#        region: "{{ aws_region }}"
#        description: Secrets security group
#        vpc_id: "{{vpc.vpc.id}}"
#        tags:
#          Name: ans-secrets-sg
#          Project: 5
#        rules:
#          - proto: tcp
#            group_name:
#              - ans-secrets-tag-sg
#              - ans-development-sg
#            cidr_ip: 0.0.0.0/0
#            rule_desc: allow all from secrets and dev sg's
#        state: present
#      register: secrets_sg
#
#    - name: Create secrets tag security group
#      ec2_group:
#        name: ans-secrets-tag-sg
#        region: "{{ aws_region }}"
#        description: Secrets tag  security group
#        vpc_id: "{{vpc.vpc.id}}"
#        tags:
#          Name: ans-secrets-tag-sg
#          Project: 5
#        rules:
#          - proto: tcp
#            ports: all
#            group_name: ans-development-sg
#            rule_desc: allow all from development
#        rules_egress:
#          - proto: tcp
#            ports: all
#            group_name: ans-secrets-sg
#        state: present
#      register: secrets_tag_sg
#
#    - name: Create postgres security group
#      ec2_group:
#        name: ans-postgres-sg
#        region: "{{ aws_region }}"
#        description: Postgres security group
#        vpc_id: "{{vpc.vpc.id}}"
#        tags:
#          Name: ans-postgres-sg
#          Project: 5
#        rules:
#          - proto: tcp
#            ports: 5432
#            group_name: ans-postgres-tag-sg
#            rule_desc: allow all from postgres tag
#        state: present
#      register: postgres_sg
#
#    - name: Create postgres security group
#      ec2_group:
#        name: ans-postgres-tag-sg
#        region: "{{ aws_region }}"
#        description: Postgres tag security group
#        vpc_id: "{{vpc.vpc.id}}"
#        tags:
#          Name: ans-postgres-tag-sg
#          Project: 5
#        rules_egress:
#          - proto: tcp
#            ports: 5432
#            group_name: ans-postgres-tag-sg
#            rule_desc: allow to postgres
#        state: present
#      register: postgres_tag_sg
#
