- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Provision Db Instance
      ec2:
        key_name: zum
        assign_public_ip: yes
        user_data: "{{ lookup('file', './ec2-scripts/ec2-prod-bootstrap.sh') }}"
        group:
          - "{{postgres_tag_sg.group_name}}"
          - "{{nginx_sg.group_name}}"
          - "{{dev_sg.group_name}}"
        instance_type: t2.micro
        region: "{{ aws_region }}"
        image: "{{ ami_id }}"
        instance_profile_name: image-gallery-server-role
        instance_tags:
          Name: provision_postgres_instance
        vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
        exact_count: 1
        count_tag:
          Name: ans_Db_sql
      register: db_sql

    - name: debug
      debug: var=db_sql

    - name: Connect to database, create  user, and grant access to database and products table
      postgresql_user:
        db: "{{ans_rds.db_name}}"
        login_host: "{{ans_rds.ans_rds.endpoint}}"
        login_user: postgres
        login_password: tacos123
        no_password_changes: no
        priv: ALL
        user: image_gallery
        password: ceec4eif7ya
      register: db_user
    - name: debug
      debug: var=db_user

    - name:
      postgresql_table:
        name: users
        owner: image_gallery
        columns:
          - username varchar(100) primary key
          - password varchar(100)
          - full_name varchar(100)
      register: users_table

    - name: Insert query to image_gallery
      postgresql_query:
        db: image_gallery
        query: insert into users (username, password, full_name) values(%s, %s, %s);