- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Create an ec2 launch template
      ec2_launch_template:
        name: "ansible_template"
        image_id: "ami-04e59c05167ea7bd5"
        key_name: zum
        instance_type: t2.micro
        iam_instance_profile: image-gallery-server-role
        monitoring:
          enabled: yes
        network_interfaces:
          - device_index: 0
          - associate_public_ip_address: yes
          - groups:
              - "{{postgres_sg.group_id}}"
              - "{{dev_sg.group_id}}"
              - "{{nginx_sg.group_id}}"
        user_data: "{{ lookup('file', './ec2-scripts/ec2-prod-bootstrap.sh') | b64encode }}"
        state: present
      register: ans_launch_template
