- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:

  - name: Create RDS subnet group
    rds_subnet_group:
      name: ans-rds-sn-group
      description: Private subnets for rds
      subnets:
        - "{{ private_subnet_1.subnet.id }}"
        - "{{ private_subnet_2.subnet.id }}"
      state: present
    register: ans_rds_sng