- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - s3_bucket:
        name: ansible-bucket
        state: present
        tags:
          Name: Ansible S3 bucket
          Project: 5