- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Provision Db Instance
      ec2:
        key_name: zum
        assign_public_ip: yes
        user_data: "{{ lookup('file', './ec2-scripts/ec2-prod-bootstrap.sh') }}"
        group:
          - "{{postgres_tag_sg.group_name}}"
          - "{{nginx_sg.group_name}}"
          - "{{dev_sg.group_name}}"
        instance_type: t2.micro
        region: "{{ aws_region }}"
        image: "{{ ami_id }}"
        instance_profile_name: image-gallery-server-role
        instance_tags:
          Name: provision_postgres_instance
        vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
        exact_count: 1
        count_tag:
          Name: ans_Db_sql
      register: db_sql

    - name: debug
      debug: var=db_sql
#
#    - name: display multiple file contents
#      slurp:
#        src: ./rds-ep.txt
#      register: ep
#
#    - name: display multiple file contents
#      slurp:
#        src: ./rds-ep.txt
#      register: rds_name
    - name: Add new instance to host group
      add_host:
        hostname: "{{item.public_ip }}"
        groupname: tag_Name_m5_buffer
      loop: "{{ db_sql.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 180
      loop: "{{ db_sql.instances }}"

           #        privs: ALL