- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    - name: Dissaociate and release eip's from ans_nlb
      ec2_eip:
       ip:
        - "{{nlb_eip_1.public_ip}}"
        - "{{nlb_eip_2.public_ip}}"
       state: absent
      register: nlb_iep_released