- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:
    name: Destroy the nlb
    elb_network_lb:
      name: "{{ans_nlb}}"
      state: absent
     register: nlb_destroy
